import { config } from 'dotenv';

config();

export const {
    GUESTY_USERNAME,
    GUESTY_PASSWORD,
    GUESTY_LISTING,
    GUESTY_ACCOUNT,
    GUESTY_API_KEY,
    AUGUST_INSTALL_ID,
    AUGUST_PASSWORD,
    AUGUST_IDENTIFIER,
    AUGUST_API_KEY,
    AUGUST_LOCK,
    GOOGLE_CREDENTIALS,
    GOOGLE_CALENDAR_ID,
    GOOGLE_SHEET_ID,
    STREAMLINE_EMAIL,
    STREAMLINE_PASSWORD
} = process.env;

export const STREAMLINE_UNIT_ID = parseInt(process.env.STREAMLINE_UNIT_ID);