name: Create Guest Access Codes

on:
  workflow_dispatch:
  schedule: 
    # 4x daily, every 6 hours
    - cron: '0 */6 * * *'

env:
  GUESTY_USERNAME: ${{ secrets.GUESTY_USERNAME }}
  GUESTY_PASSWORD: ${{ secrets.GUESTY_USERNAME }}
  GUESTY_LISTING: ${{ secrets.GUESTY_USERNAME }}
  GUESTY_ACCOUNT: ${{ secrets.GUESTY_USERNAME }}
  GUESTY_API_KEY: ${{ secrets.GUESTY_USERNAME }}
  AUGUST_INSTALL_ID: ${{ secrets.GUESTY_USERNAME }}
  AUGUST_PASSWORD: ${{ secrets.GUESTY_USERNAME }}
  AUGUST_IDENTIFIER: ${{ secrets.GUESTY_USERNAME }}
  AUGUST_API_KEY: ${{ secrets.GUESTY_USERNAME }}
  AUGUST_LOCK: ${{ secrets.GUESTY_USERNAME }}

jobs:
  run:
    runs-on: ubuntu-latest
    container: node:18-alpine
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM Install
        run: npm install

      - name: Execute
        run: node . createGuestPins