#5-1-25
name: Create Guest Access Codes

on:
  push:
  workflow_dispatch:
  schedule: 
   - cron: '0 */6 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  # STREAMLINE_EMAIL: ${{ secrets.STREAMLINE_EMAIL }}
  # STREAMLINE_PASSWORD: ${{ secrets.STREAMLINE_PASSWORD }}
  # STREAMLINE_UNIT_ID: ${{ secrets.STREAMLINE_UNIT_ID }}
  GUESTY_USERNAME: ${{ secrets.GUESTY_USERNAME }}
  GUESTY_PASSWORD: ${{ secrets.GUESTY_PASSWORD }}
  GUESTY_LISTING: ${{ secrets.GUESTY_LISTING }}
  GUESTY_ACCOUNT: ${{ secrets.GUESTY_ACCOUNT }}
  GUESTY_API_KEY: ${{ secrets.GUESTY_API_KEY }}
  AUGUST_INSTALL_ID: ${{ secrets.AUGUST_INSTALL_ID }}
  AUGUST_PASSWORD: ${{ secrets.AUGUST_PASSWORD }}
  AUGUST_IDENTIFIER: ${{ secrets.AUGUST_IDENTIFIER }}
  AUGUST_API_KEY: ${{ secrets.AUGUST_API_KEY }}
  AUGUST_LOCK: ${{ secrets.AUGUST_LOCK }}

jobs:
  run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: node:18-alpine
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM Install
        run: npm install

      - name: 3306CR
        run: node . createGuestPins
        env:
          AUGUST_LOCK: ${{ secrets.LOCK_3306_FRONT }}
				continue-on-error: true

      - name: 16F
        run: node . createGuestPins
        env:
          AUGUST_LOCK: ${{ secrets.LOCK_16F_FRONT }}
          GUESTY_LISTING: ${{ secrets.GUESTY_LISTING_16F }}
				continue-on-error: true
