name: Get Locks

on:
  workflow_dispatch:

env:
  AUGUST_INSTALL_ID: ${{ secrets.AUGUST_INSTALL_ID }}
  AUGUST_PASSWORD: ${{ secrets.AUGUST_PASSWORD }}
  AUGUST_IDENTIFIER: ${{ secrets.AUGUST_IDENTIFIER }}
  AUGUST_API_KEY: ${{ secrets.AUGUST_API_KEY }}

jobs:
  run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: node:18-alpine
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM Install
        run: npm install

      - name: Locks
        run: node . getLocks
